language: node_js
sudo: false
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
install:
- npm install -g athena2
- npm install
script:
- ath2 build
# - npm run deploy "${TRAVIS_PULL_REQUEST}"
after_script:
  - cd ./dist
  - git init
  - git config user.name "ltp11"
  - git config user.email "823285635@qq.com"
  - git add .
  - git commit -m "Update sites"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages
env:
  global:
  - CXX: g++-4.8
  - GH_REF: github.com/NervJS/taro-website.git
  - GH_TOKEN: e16397116be21c14cc29a50b15917ba4848932a6
