language: node_js
sudo: false
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
install:
- npm install -g athena2
- npm install
script:
- ath2 build
- npm run deploy "${TRAVIS_PULL_REQUEST}"
env:
  global:
  - CXX: g++-4.8
  - GH_REF: github.com/NervJS/taro-website.git
